FROM python:3.9

WORKDIR /app

COPY requirements.fastapi .
RUN pip install --no-cache-dir -r requirements.fastapi

COPY ./app /app

ENV PYTHONPATH=/app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]